#!/usr/bin/env python3

import requests
import sys


subdomain_file = sys.stdin
#TODO: make filename optional arg with argparse
filename = sys.argv[1]

domain_list = iter([i.rstrip("\n") for i in subdomain_file])

for url in domain_list:
    try:
        with requests.get(url) as requesting:
            headers = requesting.headers
            if (
                "HIT"
                or "MISS" in headers
                and (
                    "X-Cache"
                    or "Cf-Cache-Status"
                    or "Age"
                    or "X-Drupal-Cache"
                    or "X-Cache-Hits"
                    or "X-Drupal-Dynamic-Cache"
                    or "Cf-Ray"
                    or "Vary"
                    or "Strict-Transport-Security: max-age"
                    or "Varnish"
                    or "varnish"
                    or "CloudFlare"
                    or "Fastly" in headers
                )
            ):
                print(f"{url} - May Be Cached\n")
                with open(filename, "a") as cachedlist:
                    cachedlist.write(f"{url}\n")
    except:
        print(f"{url} - Network Error\n")
        next()
        continue
